# MegaCreative Configuration File

# Настройки миров
worlds:
  max_worlds_per_player: 5     # Максимум миров на игрока
  world_border_size: 300       # Размер границы мира в блоках
  autoSave: true               # Автосохранение миров
  autoSaveInterval: 300        # Интервал автосохранения в секундах

# Настройки кодинга
coding:
  max_script_size: 100         # Максимальный размер скрипта (в блоках)
  max_execution_time: 5000     # Максимальное время выполнения (мс)
  enable_debug: false          # Включить отладку скриптов

# Настройки безопасности
security:
  allowed_commands:
    - "say"
    - "tell"
    - "msg"
    - "me"
    - "gamemode"
    - "tp"
    - "teleport"
    - "give"
    - "effect"
    - "playsound"
    - "particle"
    - "title"
    - "actionbar"

# Сообщения плагина
messages:
  prefix: "§8[§bMegaCreative§8] "
  noPermission: "§cУ вас нет прав на это действие!"
  worldNotFound: "§cМир не найден!"
  worldLimitReached: "§cВы достигли лимита миров!"
  worldCreated: "§aМир успешно создан!"
  worldDeleted: "§aМир успешно удален!"
  playerNotFound: "§cИгрок не найден!"
  alreadyInWorld: "§cВы уже находитесь в этом мире!"
  worldPrivate: "§cЭтот мир приватный!"
  
# Настройки GUI
gui:
  updateInterval: 20           # Интервал обновления GUI в тиках
  
# Настройки разработки
development:
  enableDebug: false           # Включить отладочные сообщения
  logWorldActions: true        # Логировать действия с мирами
