# MegaCreative Configuration File

# Настройки миров
worlds:
  max_worlds_per_player: 5     # Максимум миров на игрока
  world_border_size: 300       # Размер границы мира в блоках
  autoSave: true               # Автосохранение миров
  autoSaveInterval: 300        # Интервал автосохранения в секундах

# Настройки кодинга
coding:
  max_script_size: 100         # Максимальный размер скрипта (в блоках)
  max_execution_time: 5000     # Максимальное время выполнения (мс)
  max_recursion_depth: 50      # Максимальная глубина рекурсии
  max_concurrent_scripts: 20   # Максимальное количество одновременно выполняемых скриптов на игрока
  enable_debug: false          # Включить отладку скриптов
  
  # Пороги производительности
  performance:
    slow_execution_threshold: 50      # Порог медленного выполнения (мс)
    memory_warning_threshold: 104857600 # Порог предупреждения о памяти (100 МБ в байтах)
    max_iterations: 1000              # Максимальное количество итераций для циклов
    cleanup_interval: 300             # Интервал очистки метрик (секунды)

# Настройки безопасности
security:
  allowed_commands:
    - "say"
    - "tell"
    - "msg"
    - "me"
    - "gamemode"
    - "tp"
    - "teleport"
    - "give"
    - "effect"
    - "playsound"
    - "particle"
    - "title"
    - "actionbar"
  
  # Враждебные игроки, которым запрещен доступ к мирам Creative+
  enemy_players:
    - "stormovx"
    - "FernyaL"
    - "GromoverGets"
    - "GromoverNone"
    - "AlexRadievskiy"
    - "Apotheoses"
    - "MrArtur4Ik"
    - "MrArthur4Ik"
    - "savaksp2547660"
    - "zeekyo_"
  
  # Игроки с ограниченным доступом к кодированию и мирам
  restricted_players:
    - "TimePlay"
    - "nosatlev"

# Сообщения плагина
messages:
  prefix: "§8[§bMegaCreative§8] "
  noPermission: "§cУ вас нет прав на это действие!"
  worldNotFound: "§cМир не найден!"
  worldLimitReached: "§cВы достигли лимита миров!"
  worldCreated: "§aМир успешно создан!"
  worldDeleted: "§aМир успешно удален!"
  playerNotFound: "§cИгрок не найден!"
  alreadyInWorld: "§cВы уже находитесь в этом мире!"
  worldPrivate: "§cЭтот мир приватный!"
  
# Настройки GUI
gui:
  updateInterval: 20           # Интервал обновления GUI в тиках
  
# Настройки разработки
development:
  enableDebug: false           # Включить отладочные сообщения
  logWorldActions: true        # Логировать действия с мирами
