biggest-id: 0
# Телепортировать игрока после кика из мира:
kick-to: "world"

# Прошу поддержать проект vk.com/framelandnetwork
# Да, простое выживание и анархия, но зато дружелюбный админ
# Без грифа, ламповая атмосфера и при желании можно заниматся РП

message:
  setName:
    - "&e Напишите в чат, какое бы вы хотели название мира"
    - "&7 (cancel для отмены):"
  setDescription:
    - "&e Напишите в чат, какое бы вы хотели описание к миру"
    - "&7 (cancel для отмены, stop для того, чтобы закончить писать описание)"
  setID:
    - "&e Напишите в чат, какой бы вы хотели айди мира"
    - "&7 (cancel для отмены):"

# Название мира: #name#
# Цифровой ID мира: #cID#
# Буквенный ID мира: #bID#
# Доступность мира: #avail#
# Описание к миру: #desc#
## # Описание всегда должно быть в конце. к #desc# также относится
fullInformation:
  - "&f Название мира: #name#"
  - "&f Цифровой ID мира: #cID#"
  - "&f Буквенный ID мира: #bID#"
  - "&f Доступность мира: #avail#"
  - "&f Описание к миру: #desc#"

##Названия и описания предметов в меню
#
# Название мира
nameName: "&dУстановить название мира"
nameDescription:
  - ""
  - "&7Нажмите, чтобы сменить название мира (Не больше 26 символов)"
  - ""
#
# Описание мира
descName: "&dУстановить описание мира"
descDescription:
  - ""
  - "&7Нажмите, чтобы сменить описание мира (Не больше 6-и строк по 26 символов)"
  - ""
#
# Cпавн мира
spawnName: "&dУстановить точку возрождения"
spawnDescription:
  - ""
  - "&7Нажмите, чтобы установить точку возрождения в мире"
  - ""
#
# Айди мира
idName: "&dУстановить ID мира"
idDescription:
  - ""
  - "&7Нажмите, чтобы установить айди мира (не больше 17 символов)"
  - ""
#
# Доступность мира
closeName: "&dУстановить доступность мира"
closeDescriptionOpened:
  - ""
  - "&7Мир открыт"
  - "&7Нажмите, чтобы включить/отключить доступность в миру"
  - ""
closeDescriptionClosed:
  - ""
  - "&7Мир закрыт"
  - "&7Нажмите, чтобы включить/отключить доступность в миру"
  - ""
#
# Правила мира
ruleName: "&dУстановить игровые правила"
ruleDescription:
  - ""
  - "&7Нажмите, чтобы открыть меню с игровыми правилами"
  - ""
#
# Кикнуть человека
kickName: "&dВыгнать игрока"
kickDescription:
  - ""
  - "&7Нажмите, чтобы выгнать игрока"
  - ""
#
# Белый список
whiteName: "&dБелый список"
whiteDescription:
  - ""
  - "&7Нажмите [ЛКМ], чтобы добавить игрока в белый список"
  - "&7Нажмите [ПКМ], чтобы убрать игрока из белого списка"
  - ""
#
# Чёрный список
blackName: "&dЧёрный список"
blackDescription:
  - ""
  - "&7Нажмите [ЛКМ], чтобы добавить игрока в чёрный список"
  - "&7Нажмите [ПКМ], чтобы убрать игрока из чёрного списка"
  - ""
#
# Игра
playName: "&dПерейти в игровой режим"
playDescription:
  - ""
  - "&7Нажмите, чтобы перейти в игровой режим"
  - ""
#
# Код
codeName: "&dПерейти в режим разработчика"
codeDescription:
  - ""
  - "&7Нажмите, чтобы зайти в код"
  - ""
#
# Информация
infoName: "&eИнформация о режиме"
infoDescription:
  - ""
  - "&7Лайков: &e#liked#"
  - "&7Уникальных поситителей: &e#uni#"
  - ""
  - "&7ID: &e#id#"
#
# Все игры
gamesName: "&dОткрыть меню с играми"
gamesDescription:
  - ""
  - "&7Нажмите, чтобы открыть меню с другими играми от игроков"
  - ""
gameRules:
  randomTickSpeed: "&9randomTickSpeed"
  rts-description:
    - ""
    - "&7Значение: &b#value#"
    - ""
    - "&7Нажмите, чтобы установить значение для randomTickSpeed"
    - "&8&oЧастота происхождения такта блоков"
    - "&8&oнапример: рост растений, исчезновение листвы"
    - ""
    - "&7(Число от -9999 до 9999), cancel для отмены"
    - "&7Чтобы вернуть значение обратно, введите число 3"
  rts-message:
    - "&fНапишите в чат новое значение для игрового правила"
    - "&erandomTickSpeed &7(cancel для отмены)"
  doDaylightCycle: "&9doDaylightCycle"
  ddlc-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &edoDaylightCycle"
    - "&8&oСменя дня и ночи"
  doEntityDrops: "&9doEntityDrops"
  ded-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &edoEntityDrops"
    - "&8&oВыпадение предметов с сущностей"
  showDeathMessages: "&9showDeathMessages"
  sdm-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &eshowDeathMessages"
    - "&8&oОтображение сообщений о смерти"
  naturalRegeneration: "&9naturalRegeneration"
  nr-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &enaturalRegeneration"
    - "&8&oРегенерация здоровья с помощью сытости"
  mobGriefing: "&9mobGriefing"
  mg-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &emobGriefing"
    - "&8&oИзменение блоков и подбор вещей мобами"
  keepInventory: "&9keepInventory"
  ki-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &ekeepInventory"
    - "&8&oСохранение инвентаря игрока после смерти"
  doWeatherCycle: "&9doWeatherCycle"
  dwc-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &edoWeatherCycle"
    - "&8&oСмена погоды в мире"
  doMobLoot: "&9doMobLoot"
  dml-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &edoMobLoot"
    - "&8&oВыпадение предметов и опыта с мобов после смерти"
  doTileDrops: "&9doTileDrops"
  dtd-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &edoTileDrops"
    - "&8&oВыпадение блоков при их разрушении"
  doFireTick: "&9doFireTick"
  dft-description:
    - ""
    - "&7Значение: #value#"
    - ""
    - "&7Нажмите, чтобы изменить значение для &edoFireTick"
    - "&8&oСгорание блоков, распространение и тушение огня"
back:
  name: "&fВернутся назад"
  desc:
    - "&8Нажмите, чтобы вернутся к настройке мира"
    - ""
maxLiked:
  name: "&6По количеству лайков"
  description:
    - ""
    - "&7Нажмите, чтобы отсортировать миры по лайкам"
    - "&7&oВ убывающем порядке"
maxUniq:
  name: "&6По количеству уникальных посетителей"
  description:
    - ""
    - "&7Нажмите, чтобы отсортировать миры по уникальным игрокам"
    - "&7&oВ убывающем порядке"
newest:
  name: "&6По недавно созданным"
  description:
    - ""
    - "&7Нажмите, чтобы остортировать миры по дате создания"
    - "&7&o(Новейшие)"
liked:
  name: "&fПонравившееся миры"
  description:
    - ""
    - "&7Нажмите, чтобы открыть меню с понравившимися мирами"
    - ""
own:
  name: "&aСвои миры"
  description:
    - ""
    - "&7Нажмите, чтобы открыть меню со своими мирами"
    - ""
latest:
  name: "&fПоследние миры"
  description:
    - ""
    - "&7Нажмите, чтобы открыть меню с последними мирами,"
    - "&7которые вы посетили"
gameList:
  back: "&7Назад"
  front: "&7Вперёд"
#
# #author# - Автор,
# #name# - Название,
# #id# - Айди,
# #opened# - Доступность,
# #players# - Уникальных игроков,
# #likes# - Количество лайков
#

# ! # ! #
# ID Всегда должен быть на первой строке
# Разрешено менять цвета. Но лучше не трогать.
# Если удалил, тогда вот:
#       - "&8ID: &7#id#"

# Между part1 и part2 находится описание. Если хотите,
# чтобы описание находилось в конце, перенесите материал
# из part2 в part1, и так наоборот.
for-every-world:
  desc:
    part1:
      - "&8ID: &7#id#"
      - "&eЛайков: &b#likes#"
      - "&eУникальных игроков: &b#players#"
      - ""
      - "&e Описание:"
    part2:
      - ""
      - "&eАвтор: &7#author#"
      - "&eДоступность: #opened#"

# #id# - Айди,
# #author# - Автор,
# #players# - Уникальных игроков,
# #likes# - Количество лайков
for-own-world:
  desc:
    - "&8ID: &7#id#"
    - ""
    - "&eНазвание: &f#name#"
    - "&eЛайков: &b#likes#"
    - "&eУникальных игроков: &b#players#"
newWorld:
  name: "&eСоздать новый мир"
  desc:
    - ""
    - "&7Нажмите, чтобы создать свой новый мир"

# #uuid# - UUID,
# #name# - Ник игрока
kickPlayer:
  desc:
    - ""
    - "&7UUID: &3#uuid#"
    - "&7Ник: #name#"

# #uuid# - UUID,
# #name# - Ник игрока
whitePlayer:
  desc:
    - ""
    - "&7UUID: &3#uuid#"
    - "&7Ник: #name#"

# #uuid# - UUID,
# #name# - Ник игрока
blackPlayer:
  desc:
    - ""
    - "&7UUID: &3#uuid#"
    - "&7Ник: #name#"
compass:
  player:
    name: "&eНайти игру"
    desc:
      - ""
      - "&8Нажмите, чтобы открыть меню с другими играми"
  dev:
    name: "&eНастройки игры"
    desc:
      - ""
      - "&8Нажмите, чтобы открыть меню с настройками игры"

CODE:
  blocks:
    diamond:
      name: "&bСобытие игрока"
      desc:
        - "&fтекст"
    cobblestone:
      name: "&7Действие игрока"
      desc:
        - "&fтекст"
    wood:
      name: "&eЕсли игрок"
      desc:
        - "&fтекст"
    nether-brick:
      name: "&cДействие события"
      desc:
        - "&fтекст"
    lapis:
      block:
        name: "&9Функция"
        desc:
          - "&fтекст"
      ore:
        name: "&9Использовать функции"
        desc:
          - "&fтекст"
    ender-stone:
      name: "&eИначе"
      desc:
        - "&fтекст"
    piston:
      name: "&dСкобка"
      desc:
        - "&7Вспомогательный блок."
        - "&7Если случайно сломал/нужно пометить строчку"
  items:
    values:
      name: "&fПеременные"
      desc:
        - ""
        - "&fтекст"
        - ""
    codeSwap:
      name: "&6Перемещатель кода"
      desc:
        - ""
        - "&fшифт+пкм = назад"
        - "&fпкм = вперёд"
        - "&fпользуйся этим, дурачёк."
        - ""
        - "&fне нужно хуярить пол кода для того,"
        - "&fчтобы вставить функцию"
    arrowNO:
      name: "&fСтрелка &cНЕ"
      desc:
        - ""
        - "&9онли для проверок"
        - ""
    codeFloors:
      name: "&eДобавить этаж кода (максимум 8)"
      desc:
        - ""
        - "&7Нажмите, чтобы добавить этаж к коду"
        - ""
CODE_GUI:
  name:
    name: "&bТекстовая переменная"
    desc:
      - "&btext"
      - "&7 ass we can"
  var:
    name: "&bЧисловая переменная"
    desc:
      - "&btext"
      - "&7 ass we can"
  coord:
    name: "&bКоординаты"
    desc:
      - "&btext"
      - "&7 ass we can"
  apple:
    name: "&cЯБЛОЧКО OWO OWO"
    desc:
      - "&btext"
      - "&7 ass we can"
  info:
    name: "&cинформация какаята"
    desc:
      - "&dпридумай"
      - "&7придумай"

# #id# - айди
scoreboard:
  world:
    name: "&6Игра от игрока"
    lore:
      - "&7ID: #id#"
      - ""
      - "vk.com/framelandnetwork"
  code:
    name: "&9Код"
    lore:
      - "Код-код-код"
      - ""
      - "&7ID: #id#"
      - "vk.com/framelandnetwork"

apple:
  gui-name: "ЯБЛОЧКОЧКЧКТАЛЫВАОЬЫЛВА"
  a:
    name: "значения сущности"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 260
  b:
    name: "значения события"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 264
  c:
    name: "значения игры"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 337

  # значения сущности
  d:
    name: "текущее здоровье"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  e:
    name: "максимальное здоровье"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  f:
    name: "текущий уровень голода"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  g:
    name: "текущий уровень сытости"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  h:
    name: "текущий уровень опыта"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  i:
    name: "текущий уровень защиты"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  j:
    name: "текущий уровень воздуха"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  k:
    name: "текущий слот"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  l:
    name: "пинг игрока"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  m:
    name: "целевой блок"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  n:
    name: "текущее местоположение"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  o:
    name: "название открытого инвентаря"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  p:
    name: "местоположение целевого блока"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  q:
    name: "текущий предмет"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  r:
    name: "предмет из второй руки"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339

  # значения события
  s:
    name: "урон"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  t:
    name: "кликнутый слот"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  u:
    name: "новый слот"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  v:
    name: "старый слот"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  w:
    name: "сообщение игрока"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  x:
    name: "местоположение блока"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  y:
    name: "кликнутый предмет"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  z:
    name: "блок с события"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339

  # значения игры
  aa:
    name: "количество игроков"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  ab:
    name: "количество лайков в игре"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  ac:
    name: "количество уникальных посетителей"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339
  ad:
    name: "айди мира"
    lore:
      - "бульбуль"
      - "буль"
    material-id: 339